### ISSUE TITLE
npm install sha3 fails (node 13.x)

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/WrappedETC#5]
**Describe the bug**
```sh
> npm i

> sha3@1.2.3 install /home/ia/dev/bakaoh/WrappedETC/node_modules/sha3
> node-gyp rebuild

make: Entering directory '/home/ia/dev/bakaoh/WrappedETC/node_modules/sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
../src/addon.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE SHA3Hash::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/addon.cpp:49:23: warning: ‘new’ of type ‘SHA3Hash’ with extended alignment 32 [-Waligned-new=]
    obj = new SHA3Hash();
                       ^
../src/addon.cpp:49:23: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
../src/addon.cpp:49:23: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
../src/addon.cpp: In static member function ‘static void SHA3Hash::Init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/addon.cpp:83:27: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>&, v8::Local<v8::Function>&)’
   target->Set(className, f);
                           ^
In file included from /home/ia/.cache/node-gyp/13.6.0/include/node/node.h:63:0,
                 from ../src/addon.cpp:1:
/home/ia/.cache/node-gyp/13.6.0/include/node/v8.h:3547:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/ia/.cache/node-gyp/13.6.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/ia/.cache/node-gyp/13.6.0/include/node/v8.h:3550:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/ia/.cache/node-gyp/13.6.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
sha3.target.mk:115: recipe for target 'Release/obj.target/sha3/src/addon.o' failed
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
make: Leaving directory '/home/ia/dev/bakaoh/WrappedETC/node_modules/sha3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ia/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.2.9-050209-generic
gyp ERR! command "/home/ia/.nvm/versions/node/v13.6.0/bin/node" "/home/ia/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ia/dev/bakaoh/WrappedETC/node_modules/sha3
gyp ERR! node -v v13.6.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN wetc@1.0.0 No repository field.
npm WARN wetc@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ia/.npm/_logs/2020-05-21T11_34_53_249Z-debug.log

```

**To Reproduce**
```sh
npm install
```

**Expected behavior**
Installs dependencies.

**Desktop (please complete the following information):**
```sh
> node -v
v13.6.0
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

**Additional context**
https://github.com/phusion/node-sha3/issues/32

**Comment by meowsbits** [comment]
downgrading node to 9.11.1 solves it

**Comment by ArinCantCode** [comment]
still an issue on node 14.4.0 and 12.18.2
