### ISSUE TITLE
Error: Returned values aren't valid, did it run Out of Gas?

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/WrappedETC#6]
on branch ` wipwipwip-merge-wipwip`

```sh
> node -v
v9.11.1
```

```sh
> ./build/bin/geth --dev --miner.gaslimit 18000000 --miner.gasprice 1 --keystore ~/dev/bakaoh/WrappedETC/keystore/ --http --http.port 7545 --verbosity 5 console 2> geth.log

> ./build/bin/geth --dev --miner.gaslimit 18000000 --miner.gasprice 1 --keystore ~/dev/bakaoh/WrappedETC/keystore/ --http --http.port 7545 --verbosity 5 console 2> geth.log
Welcome to the Geth JavaScript console!

instance: CoreGeth/v1.11.5-unstable-a31ca3b5-20200520/linux-amd64/go1.13.5
coinbase: 0x7d38c531e7544625a4ea96437d7fe5c2918f3307
at block: 0 (Wed Dec 31 1969 18:00:00 GMT-0600 (CST))
 datadir:
 modules: admin:1.0 clique:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 shh:1.0 txpool:1.0 web3:1.0

> eth.accounts
["0x7d38c531e7544625a4ea96437d7fe5c2918f3307"]
> eth.getBalance(eth.accounts[0])
1.15792089237316195423570985008687907853269984665640564039457584007913129639927e+77
> eth.getBalance(eth.accounts[0])
1.15792089237316195423570985008687907853269984665640564039457584007913129639927e+77

```

```sh
> sudo truffle migrate --network og
private key 6f9b706e49544e3b077502cedde75aab57893a4a3c2e08a7ac69e55ec2dc9682
Compiling ./contracts/Address.sol...
Compiling ./contracts/ERC777.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/WrappedETCToken.sol...
Compiling @openzeppelin/contracts/GSN/Context.sol...
Compiling @openzeppelin/contracts/introspection/IERC1820Registry.sol...
Compiling @openzeppelin/contracts/math/SafeMath.sol...
Compiling @openzeppelin/contracts/token/ERC20/IERC20.sol...
Compiling @openzeppelin/contracts/token/ERC777/IERC777.sol...
Compiling @openzeppelin/contracts/token/ERC777/IERC777Recipient.sol...
Compiling @openzeppelin/contracts/token/ERC777/IERC777Sender.sol...
Writing artifacts to ./client/src/contracts

Error: Returned values aren't valid, did it run Out of Gas?
    at ABICoder.decodeParameters (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/src/index.js:226:1)
    at Contract._decodeMethodReturn (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:465:1)
    at Method.outputFormatter (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:818:1)
    at Method.formatOutput (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/~/web3-core-method/src/index.js:163:1)
    at sendTxCallback (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/~/web3-core-method/src/index.js:473:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3-core-requestmanager/src/index.js:147:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-providers-http/src/index.js:91:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:289:47)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Truffle v5.0.0-beta.2 (core: 5.0.0-beta.2)
Solidity v0.5.0 (solc-js)
Node v8.10.0
```

```
DEBUG[05-21|08:18:35.097] Served eth_getBlockByNumber              conn=127.0.0.1:41938 reqid=4                t="77.073µs"
DEBUG[05-21|08:18:35.104] Executing EVM call finished              runtime="174.618µs"
DEBUG[05-21|08:18:35.104] Served eth_call                          conn=127.0.0.1:41938 reqid=5                t="297.583µs"
DEBUG[05-21|08:18:52.810] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[05-21|08:19:09.930] Served eth_getBlockByNumber              conn=127.0.0.1:41942 reqid=4622728611077029 t="186.62µs"
DEBUG[05-21|08:19:09.937] Served eth_getBlockByNumber              conn=127.0.0.1:41944 reqid=4622728611077030 t="37.029µs"
DEBUG[05-21|08:19:09.966] Served net_version                       conn=127.0.0.1:41946 reqid=1                t="18.499µs"
DEBUG[05-21|08:19:09.968] Served eth_accounts                      conn=127.0.0.1:41946 reqid=2                t="20.262µs"
DEBUG[05-21|08:19:09.985] Served eth_getBlockByNumber              conn=127.0.0.1:41948 reqid=3                t="82.949µs"
DEBUG[05-21|08:19:09.989] Served eth_getBlockByNumber              conn=127.0.0.1:41948 reqid=4                t="75.023µs"
DEBUG[05-21|08:19:09.999] Executing EVM call finished              runtime="122.905µs"
DEBUG[05-21|08:19:09.999] Served eth_call                          conn=127.0.0.1:41948 reqid=5                t="208.871µs"
DEBUG[05-21|08:19:12.810] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[05-21|08:19:32.810] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[05-21|08:19:52.388] FS scan times                            list="81.828µs" set="9.976µs" diff="4.809µs"
TRACE[05-21|08:19:52.388] Handled keystore changes                 time="75.423µs"
DEBUG[05-21|08:19:52.811] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[05-21|08:20:12.811] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[05-21|08:20:32.811] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[05-21|08:20:52.811] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[05-21|08:21:12.812] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[05-21|08:21:32.812] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[05-21|08:21:52.352] Served eth_getBlockByNumber              conn=127.0.0.1:41980 reqid=5859590626228805 t="186.231µs"
DEBUG[05-21|08:21:52.360] Served eth_getBlockByNumber              conn=127.0.0.1:41982 reqid=5859590626228806 t="38.656µs"
DEBUG[05-21|08:21:52.812] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[05-21|08:21:56.916] Served eth_getBlockByNumber              conn=127.0.0.1:41984 reqid=5859590626228807 t="29.317µs"
DEBUG[05-21|08:21:56.951] Served net_version                       conn=127.0.0.1:41986 reqid=1                t="18.613µs"
DEBUG[05-21|08:21:56.954] Served eth_accounts                      conn=127.0.0.1:41986 reqid=2                t="19.808µs"
DEBUG[05-21|08:21:57.064] Served eth_getBlockByNumber              conn=127.0.0.1:41988 reqid=3                t="139.594µs"
DEBUG[05-21|08:21:57.069] Served eth_getBlockByNumber              conn=127.0.0.1:41988 reqid=4                t="117.396µs"
DEBUG[05-21|08:21:57.077] Executing EVM call finished              runtime="171.854µs"
DEBUG[05-21|08:21:57.077] Served eth_call                          conn=127.0.0.1:41988 reqid=5                t="270.169µs"
DEBUG[05-21|08:22:12.812] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[05-21|08:22:32.813] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[05-21|08:22:52.813] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[05-21|08:23:12.814] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[05-21|08:23:22.435] Served eth_accounts                      reqid=12               t="84.871µs"
TRACE[05-21|08:23:22.435] Handled RPC response                     reqid=12               t="2.693µs"
DEBUG[05-21|08:23:22.436] Served eth_getBalance                    reqid=13               t="225.521µs"
TRACE[05-21|08:23:22.436] Handled RPC response                     reqid=13               t="2.411µs"
```

**Comment by meowsbits** [comment]
maybe an issue with web3 ? 
```
at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3-core-requestmanager/src/index.js:147:1
```

**Comment by abcoathup** [comment]
Is the ERC1820 Registry deployed on the network at 0x1820a4B7618BdE71Dce8cdc73aAB6C95905faD24

ERC777 uses the ERC1820 Registry.

**Comment by meowsbits** [comment]
Wow @abcoathup you are on your game! I don't know where you came from, but I'm thrilled to have you here!

Indeed, I had commented the 1820 deployment (I was having issues with the npm import). I've resolved the import issues, and reinstated the following code:

```js
const WrappedETCToken = artifacts.require('WrappedETCToken');

require('openzeppelin/test-helpers/configure')({ provider: web3.currentProvider, environment: 'truffle' });
const { singletons } = require('openzeppelin/test-helpers');

module.exports = async function (deployer, network, accounts) {
  if (network === 'development') {
    // In a test environment an ERC777 token requires deploying an ERC1820 registry
    console.log('using development network');
    await singletons.ERC1820Registry(accounts[0]);
  }

  await deployer.deploy(WrappedETCToken);
};
```

However, as of 2c6a97ec99dd8a7c5c0549a1e77fd01cd8926e65 I continue to see the same issue as above. For reference, I'm on this branch: https://github.com/etclabscore/WrappedETC/commits/wipwipwip-rebase-wipwip. 

(Note I've update the migration command to use the `--network development`):

```sh
> sudo truffle migrate --network development
private key 6f9b706e49544e3b077502cedde75aab57893a4a3c2e08a7ac69e55ec2dc9682
Error: Returned values aren't valid, did it run Out of Gas?
    at ABICoder.decodeParameters (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/src/index.js:226:1)
    at Contract._decodeMethodReturn (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:465:1)
    at Method.outputFormatter (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:818:1)
    at Method.formatOutput (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/~/web3-core-method/src/index.js:163:1)
    at sendTxCallback (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/~/web3-core-method/src/index.js:473:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3-core-requestmanager/src/index.js:147:1
    at /home/ia/dev/bakaoh/WrappedETC/node_modules/web3-provider-engine/index.js:159:9
    at /home/ia/dev/bakaoh/WrappedETC/node_modules/async/internal/once.js:12:16
    at replenish (/home/ia/dev/bakaoh/WrappedETC/node_modules/async/internal/eachOfLimit.js:61:25)
    at /home/ia/dev/bakaoh/WrappedETC/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/home/ia/dev/bakaoh/WrappedETC/node_modules/async/eachLimit.js:43:36)
    at /home/ia/dev/bakaoh/WrappedETC/node_modules/async/internal/doLimit.js:9:16
    at end (/home/ia/dev/bakaoh/WrappedETC/node_modules/web3-provider-engine/index.js:134:5)
    at Request._callback (/home/ia/dev/bakaoh/WrappedETC/node_modules/web3-provider-engine/subproviders/rpc.js:62:5)
    at Request.self.callback (/home/ia/dev/bakaoh/WrappedETC/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/ia/dev/bakaoh/WrappedETC/node_modules/request/request.js:1154:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/ia/dev/bakaoh/WrappedETC/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Truffle v5.0.0-beta.2 (core: 5.0.0-beta.2)
Solidity v0.5.0 (solc-js)
Node v8.10.0

> node -v
v9.11.1

> npm -v
5.6.0

> solc --version
solc, the solidity compiler commandline interface
Version: 0.6.9-develop.2020.5.20+commit.32bec6b3.Linux.g++
```

```json
  "dependencies": {
    "@openzeppelin/contracts": "^2.4.0",
    "@openzeppelin/test-helpers": "^0.5.3",
    "chai": "^4.2.0",
    "truffle-hdwallet-provider": "^1.0.17"
  },
  "devDependencies": {
    "@openzeppelin/test-helpers": "^0.5.5",
    "chai": "^4.2.0",
    "keythereum": "^1.0.4",
    "solc-js": "^0.5.5",
    "truffle-privatekey-provider": "^1.3.0"
  },
```
